### ISSUE TITLE
Fantastic theme: how to change the background?

### ISSUE THREAD

**Issue by aferraz** [basnijholt/lovelace-ios-dark-mode-theme#1]
Hi,
 you make a very good job, the only thing I didn't understand is how to change the background.

Thanks
 Alessandro

**Comment by basnijholt** [comment]
Hi! Thanks a lot for using [the iOS Dark Mode Theme](https://github.com/basnijholt/lovelace-ios-dark-mode-theme/).

I've updated the [`backgrounds/README.md`](https://raw.githubusercontent.com/basnijholt/lovelace-ios-dark-mode-theme/master/backgrounds/README.md) file with better instructions.

Let me know if it works for you.

P.S. don't forget to ⭐️ the repo! 😇

**Comment by aferraz** [comment]
Starred but doesn't work after last commit.

**Comment by basnijholt** [comment]
It works for me. Did you try restarting your HA?

**Comment by aferraz** [comment]
Work after restart. Thanks
