### ISSUE TITLE
Switches in Horizontal stack are white even they are On

### ISSUE THREAD

**Issue by misosec** [basnijholt/lovelace-ios-dark-mode-theme#10]
Hello,
switches in Horizontal stack are white even they are On. How can I fix it?

Thank you.

**Comment by basnijholt** [comment]
Could you post a screenshot of what you mean?

**Comment by misosec** [comment]
Sure!
iOS theme
![ios_theme](https://user-images.githubusercontent.com/29805226/69493515-cecf9e00-0eaf-11ea-8028-babdd8dc0f6c.png)
Slate theme (switches are white when off)
![slate_theme](https://user-images.githubusercontent.com/29805226/69493516-d1ca8e80-0eaf-11ea-8866-6ccf2a103f51.png)

**Comment by basnijholt** [comment]
If you change this line: https://github.com/basnijholt/lovelace-ios-dark-mode-theme/blob/c9edd429cfc8e25aefb020b06da76fe410512206/themes/ios-dark-mode.yaml#L28 and use the color in the comment, you will get what you want (I think)!

**Comment by misosec** [comment]
That's it! Thank you!

**Comment by codypet** [comment]
> If you change this line:
> 
> https://github.com/basnijholt/lovelace-ios-dark-mode-theme/blob/c9edd429cfc8e25aefb020b06da76fe410512206/themes/ios-dark-mode.yaml#L28
> 
> and use the color in the comment, you will get what you want (I think)!

Could you elaborate on the color in the comment? Are you saying change #FFF to rgba(255,214,10,1)? Do I need to restart HA for this to take effect?
