### ISSUE TITLE
Sensor card lines are not visible

### ISSUE THREAD

**Issue by TinusK** [basnijholt/lovelace-ios-dark-mode-theme#11]
Using this theme, lines on the sensor card are not visible.

**Comment by basnijholt** [comment]
Could you post a screenshot of what you mean?

**Comment by TinusK** [comment]
![image](https://user-images.githubusercontent.com/27996194/69493434-e2c6d000-0eae-11ea-8260-286ae6632c05.png)
![image](https://user-images.githubusercontent.com/27996194/69493441-f70acd00-0eae-11ea-8acf-83077aacac7e.png)

**Comment by TinusK** [comment]
As you can see. No line is drawn.

**Comment by basnijholt** [comment]
What is the type of that card?

And don't forget to star the repo 🌟 😃

**Comment by TinusK** [comment]
Sure :)

From code editor in lovelace:
entity: sensor.br_temperature
graph: line
name: Buiten temperatuur
type: sensor

**Comment by basnijholt** [comment]
I have just pushed a fix!

Let me know if it doesn't work, or reopen the issue.

**Comment by TinusK** [comment]
Perfect. Thank you, it works :-)
![image](https://user-images.githubusercontent.com/27996194/69493685-edcf2f80-0eb1-11ea-83c2-02cf84c5842f.png)
