### ISSUE TITLE
Light buttons don't toggle colour

### ISSUE THREAD

**Issue by craigrallen** [basnijholt/lovelace-ios-dark-mode-theme#13]
Hi,

Just wanted to check if there will be a fix for entity buttons changing colour? When in default theme they change from blue to yellow for when they are on, however, in the iOS theme, they just stay white.

WIll there be an update to make them change colour?

I created two cards to demonstrate, one with switches and one with the entity button. The switch shows on, but the entity isn't changing colour

![image](https://user-images.githubusercontent.com/56693437/70636856-8a295e00-1c36-11ea-8031-d93565439e7e.png)

By the way, this is my favourite theme and looks great on a tablet.

**Comment by basnijholt** [comment]
I'm happy you like it!

Don't forget to Star the repo ⭐️⭐️

I think the answer is in [this line](https://github.com/basnijholt/lovelace-ios-dark-mode-theme/blob/c9edd429cfc8e25aefb020b06da76fe410512206/themes/ios-dark-mode.yaml#L28) 😄

**Comment by craigrallen** [comment]
:)

That worked a treat, I made the colour the theme primary orange and think it looks good. Thanks for your help.

Have a good one
