### ISSUE TITLE
Not able to set as default theme after boot

### ISSUE THREAD

**Issue by AdvaitT17** [basnijholt/lovelace-ios-dark-mode-theme#16]
Hi there,

I am not able to create an automation to switch the theme after boot. Please help...

Regards

**Comment by basnijholt** [comment]
I am afraid that I cannot help you with that little information. What is the automation for example? Which version of Home Assistant are you on?

**Comment by AdvaitT17** [comment]
I want to set the as default (even after rebooting). For that I want to create an automation with call service - set frontend theme to ios-dark-mode

**Comment by basnijholt** [comment]
You don't really need to do that.

You can just set the theme by clicking on the circle with your initials in the left bottom, then select the theme.

This should persist also over restarts/reboots.

**Comment by AdvaitT17** [comment]
No..it again goes back to default home assistant theme after reboot...

**Comment by basnijholt** [comment]
Can you confirm that you can get the desired behavior when using another theme?

**Comment by AdvaitT17** [comment]
I guess it is happening because it is installed over hacs maybe. Because earlier when I installed any xyz theme(yaml) it worked with automation and also did not changed after reboot(same browser).

**Comment by basnijholt** [comment]
Well, try it with another HACS installed theme then.

It shouldn't make a difference though.

Did you follow all the installation steps correctly?

**Comment by AdvaitT17** [comment]
Yes, I did!
