### ISSUE TITLE
Icon color doesn't represent the state

### ISSUE THREAD

**Issue by chrisgott** [basnijholt/lovelace-ios-dark-mode-theme#17]
Within most cards (tested just with light and glance) the icons doesn't change their color to representate their status.

in the default theme a light (who is off) is colored in blueish tint. as activated it turn to yellowish. this does not happen in iosdarkmode - the light icons stays white. espacially in dark mode this behaviour would be very nice.

**Comment by basnijholt** [comment]
See [this](https://github.com/basnijholt/lovelace-ios-dark-mode-theme/blob/master/themes/ios-dark-mode.yaml#L28) line ;)
