### ISSUE TITLE
Error in Home Assistant - 

### ISSUE THREAD

**Issue by Scope666** [basnijholt/lovelace-ios-dark-mode-theme#19]
Hi,

Amazing theme!  Everything works as it should except the custom backgrounds feature, I can't get any of the 4 to load.  I'm following this method:  https://github.com/basnijholt/lovelace-ios-dark-mode-theme/tree/master/backgrounds

Getting this error in Home Assistant:

```
Error loading /config/configuration.yaml: while parsing a block mapping
  in "/config/themes/ios-dark-mode.yaml", line 7, column 3
expected <block end>, but found '<scalar>'
  in "/config/themes/ios-dark-mode.yaml", line 7, column 76143
```

**Comment by basnijholt** [comment]
How did you install the theme?

Did you perhaps copy paste the code into a file?

**Comment by Scope666** [comment]
I used HACS, config in Raw Config Editor looks like this:

![image](https://user-images.githubusercontent.com/31927547/72480636-0ed34300-37c6-11ea-8127-ee7d26467485.png)

I have the background as a single line at line number 7:

![image](https://user-images.githubusercontent.com/31927547/72480683-32968900-37c6-11ea-9cd2-6032918e0a5b.png)

**Comment by Scope666** [comment]
I redid the whole process again and restarted Home Assistant, this time it worked ... no idea why.  OK to close:    (this looks AWESOME!)

![image](https://user-images.githubusercontent.com/31927547/72482208-ec8ff400-37ca-11ea-9749-269e877f3bfb.png)
