### ISSUE TITLE
Suggestion: Let HACS handle the background image

### ISSUE THREAD

**Issue by ronsum232** [basnijholt/lovelace-ios-dark-mode-theme#23]
I'm by no means proficient in any of this, but if it is possible, having HACS handle background images separate from themes would be ideal.

**Comment by basnijholt** [comment]
Check out [this](https://www.reddit.com/r/homeassistant/comments/ex7mve/after_a_lot_of_love_a_muchrequested_feature_more/) Reddit post and https://github.com/basnijholt/lovelace-ios-themes!
