### ISSUE TITLE
 css background resets after each update

### ISSUE THREAD

**Issue by calas80** [basnijholt/lovelace-ios-dark-mode-theme#24]
I chose homekit-bg-4.css-base64 [https://gist.github.com/basnijholt/8bd2954969a75ca2e4a70d27e38418e4](url)

as the background. I wish this didn't change every time I update.

**Comment by misosec** [comment]
Yes! This is pretty annoying...

**Comment by basnijholt** [comment]
I recommend you guys to look at https://github.com/basnijholt/lovelace-ios-themes where you can easily change the background.
