### ISSUE TITLE
Suggetstion: add all 4 backgrounds to theme file with different names 

### ISSUE THREAD

**Issue by toporovskii** [basnijholt/lovelace-ios-dark-mode-theme#25]
Add all 4 background files to them to be able to use them simultaneously on different Lovelace tabs. 

Something like this 
background-image: "center / cover no-repeat fixed url('data:image/jpeg;base6....
background-image-r: "center / cover no-repeat fixed url('data:image/jpeg;bas....
background-image-g: "center / cover no-repeat fixed url('data:image/jpeg;bas....
background-image-b: "center / cover no-repeat fixed url('data:image/jpeg;bas.....

**Comment by basnijholt** [comment]
@toporovskii, after your suggestion I created https://github.com/basnijholt/lovelace-ios-themes.

See [this](https://www.reddit.com/r/homeassistant/comments/ex7mve/after_a_lot_of_love_a_muchrequested_feature_more/) Reddit post to see it in action!
