### ISSUE TITLE
can't change background image on HASSIO.

### ISSUE THREAD

**Issue by davidedomotica** [basnijholt/lovelace-ios-dark-mode-theme#27]
I followed what is wrote but doesn't work, the background image is the same.
i tried with the green image.

**Comment by basnijholt** [comment]
The green image is the default, so it probably wouldn't change.

**Comment by AbsolutJohan** [comment]
I’m also on hassio. After the last update I can’t change the background, it defaults on the green standard one. Ignores the background I put in the iOS-dark-mode.yaml

**Comment by davidedomotica** [comment]
i tried with a different string (not green) but still not working... i copy the string, change it as wrote in the documentation but nothing, it's always black.

**Comment by InToSSH** [comment]
I am facing the same problem, I was using the bg4, but now after the latest update, it shows only the default green background image, no matter if I have it in the theme yaml or not.

**Comment by basnijholt** [comment]
I recommend all to take a look at [this](https://www.reddit.com/r/homeassistant/comments/ex7mve/after_a_lot_of_love_a_muchrequested_feature_more/) Reddit post.

I tried to solve this problem in this repo: https://github.com/basnijholt/lovelace-ios-themes

**Comment by davidedomotica** [comment]
now it is working well, i can change the background image but the up part where i change the page is always orange.
how can i get the same image also there? and i copied your automation to switch the themes but i don't understand if i have to add something more, because nothing happen if i use your automation.
just the last thing, how can i add a different background without change the STRING everytime?
thanks a lot.

**Comment by basnijholt** [comment]
@davidedomotica, this is an issue of the other repo. I am closing this one.
