### ISSUE TITLE
Configurator Add-On & Hass.io Tab in screenshots?

### ISSUE THREAD

**Issue by D-an-W** [basnijholt/lovelace-ios-dark-mode-theme#29]
Good morning,

Not really an issue so sorry if there is a better place to ask this.

Is it Possible to get your dark and light themes to work on the Configurator Add-On and also how do I get the hass.io tab as seen in your second Overview screenshot please (It looks great)?

**Comment by basnijholt** [comment]
Unfortunately, this isn't possible :(

**Comment by D-an-W** [comment]
Hi basnijholt, sorry...I assume you mean it isn’t possible to apply your themes to the Configurator Add-On?

However, would you please be able to advise how I might reproduce the layout in your second Overview screenshot?

**Comment by basnijholt** [comment]
You mean, that you want the cards that I have used?

For that, take a look at my https://github.com/basnijholt/home-assistant-config/ files.

It includes [`lovelace-ui.yaml`](https://github.com/basnijholt/home-assistant-config/blob/master/lovelace-ui.yaml).

**Comment by D-an-W** [comment]
Yes, I think the second Hass.io tab(?) you show in the screenshots looks great and would love to reproduce it.

I don't even have a Hass.io tab at the top but will try and figure out how to do it!

**Comment by D-an-W** [comment]
It was a late night but I did make some progress, below is how it looks so far.

Would you have any ideas how I might fix Speed test please?

![Screenshot 2020-02-02 at 08 51 59](https://user-images.githubusercontent.com/2243883/73605724-c83d6100-4599-11ea-95b3-28d00386754f.png)

**Comment by D-an-W** [comment]
Hi again basnijholt, I finally het everything up and running after a late night / early morning!

I have noticed the network card sometimes ends up looking like the screenshot below, is that something I did wrong (Reloading rectifies it)...
![Screenshot 2020-02-02 at 19 35 10](https://user-images.githubusercontent.com/2243883/73614070-be484c00-45f3-11ea-915a-ec13851e4934.png)
