### ISSUE TITLE
Add support for Paper Item Icon Active color

### ISSUE THREAD

**Issue by DarkMagic** [basnijholt/lovelace-ios-dark-mode-theme#30]
Please add this code to your theme to make icon of entities display active/off status.
```paper-item-icon-active-color: "#F9C536"```

**Comment by basnijholt** [comment]
Could you perhaps provide a screenshot and point out which icons you are referring to?

**Comment by cobch** [comment]
I have the same problem. On a computer I get the icon that are active but not when I use the IOS app.
I post an exempel for the lock but it is the same for the bulb.

![image1](https://user-images.githubusercontent.com/50397676/77891958-15744100-7272-11ea-87ad-0eec47395969.jpeg)

![image0](https://user-images.githubusercontent.com/50397676/77891964-17d69b00-7272-11ea-9640-e8431dc376ab.png)

**Comment by cobch** [comment]
@basnijholt Any news about the problem on IOS with the à active function of icons? I tested on an IPad and it works there but not on IPhone. Really strange!

**Comment by basnijholt** [comment]
I've added this!

**Comment by cobch** [comment]
@basnijholt Great! I am using the alternative themes and they all works fine!
