### ISSUE TITLE
Opacity is a bit too much, changable in settings?

### ISSUE THREAD

**Issue by recklessnl** [basnijholt/lovelace-ios-dark-mode-theme#31]
Love these themes, they look absolutely amazing, but in my opinion the opacity is too much and clashes sometimes. When I open up an entity for finer control (for example, I click on a light entity's icon to see the pop-up menu, so I can change brightness), the text regularly clashes with the background and it's hard to read sometimes.

The fix is super simple: just a little bit less opacity would fix it. But since I installed this through HACS, I feel like if I manually change these, it'll get reset the next time an update comes out for these themes.

 Is there a way to toggle a global opacity for all your themes (which are great) so that it won't be reset in future updates?

**Comment by basnijholt** [comment]
There's no global switch. 

However, you could submit a PR and propose a better default? 😃

**Comment by basnijholt** [comment]
Fixed in https://github.com/basnijholt/lovelace-ios-dark-mode-theme/commit/0f050901ae2f114ae607fb402e256881ae58ca33
