### ISSUE TITLE
state-icon-active-color not working for entities of type switch

### ISSUE THREAD

**Issue by nass623** [basnijholt/lovelace-ios-dark-mode-theme#32]
I modified the settings for state-icon-active-color so that the icons will be yellow when active but i have noticed that this only works for my entities of type = light. Entities of type = switch do not change colors at all. Just as an FYI, I only use lutron caseta light switches. Thanks for all the work, I really like the way this theme looks.

**Comment by basnijholt** [comment]
In Home Assistent 0.105 this has become the default behavior.
