### ISSUE TITLE
no longer in HACS?

### ISSUE THREAD

**Issue by pznamenskii** [basnijholt/lovelace-ios-dark-mode-theme#33]
hi

it seems I am not able to locate this theme in HACS - community store's plugins section search on "ios" does not yield any results. have you removed the integration?

regards,
Pavel

**Comment by basnijholt** [comment]
You should look in the themes section.

**Comment by pznamenskii** [comment]
many thanks - apparently I did not have that section in HACS and never imagined such would exist at all. I have now enabled it under frontend section in configuration.
