### ISSUE TITLE
No Token text

### ISSUE THREAD

**Issue by lollo78** [basnijholt/lovelace-ios-dark-mode-theme#35]
Hi, if I use this theme I can't see the text inside the Token box.
![token](https://user-images.githubusercontent.com/6298682/77312645-ae4f0d80-6d02-11ea-8963-95c3cc817f6d.PNG)

How can I solve it?
Thanks

**Comment by basnijholt** [comment]
Could you reinstall the theme (I just pushed a change) and tell me if it is fixed?

**Comment by lollo78** [comment]
Hi, your fix solve the issue!
Thanks a lot
