### ISSUE TITLE
Rounding the plant-status

### ISSUE THREAD

**Issue by syphernl** [basnijholt/lovelace-ios-dark-mode-theme#4]
The [plant-status](https://www.home-assistant.io/lovelace/plant-status/) can contain an image (via customize) However, when it does have an image the top corners aren't rounded (the bottom is).

As a test I've added `border-top-left-radius: 20px` (and right) to `.has-plant-image .banner` in the console which makes the borders nicely rounded.

Not sure if this theme can alter this or whether this requires a change in the HASS Frontend to get be able to apply themes to it.

Quickfix via card-mod:
```
    style: |
      .banner {
        border-top-left-radius: 20px;
        border-top-right-radius: 20px;
      }
```

Would be nice though to be able to do this without other plugins ;-)

**Comment by basnijholt** [comment]
OK, I am happy you were able to fix it using `card-mod`.

Do you think it makes sense to add this to the theme?

**Comment by syphernl** [comment]
Because it is a "core" Lovelace card it would make sense to support it via the theme, if it is possible.Op 19 nov. 2019 18:15 schreef Bas Nijholt <notifications@github.com>:OK, I am happy you were able to fix it using card-mod.
Do you think it makes sense to add this to the theme?

**Comment by basnijholt** [comment]
Would you like to submit it as a PR? 😄 

I don't have any entities to test it against.
