### ISSUE TITLE
Problem with changing background

### ISSUE THREAD

**Issue by Brolsk** [basnijholt/lovelace-ios-dark-mode-theme#40]
I want to change the background from green to homekit-bg-4.css-base64. 
In the readme it says replace the line but im unsure of which part of the line im supposed to replace. Havent figured it out yet, can you clairfy for me? Love the theme

**Comment by TuomasPakkanen** [comment]
You need to replace the whole line 7 with the "background-image: "center / cover........really long string"

**Comment by basnijholt** [comment]
If you want to make this easier, install https://github.com/basnijholt/lovelace-ios-themes.
