### ISSUE TITLE
Colors unreadable in History Cards

### ISSUE THREAD

**Issue by sstefanowski** [basnijholt/lovelace-ios-dark-mode-theme#41]
Hello, 
I'd like to raise an issue with colours of History Card. The grid and device labels are very dark almost unreadable (marked on screenshots below). 
Can you update them to some bright colours?

Regards,

![history-card1](https://user-images.githubusercontent.com/36473471/78347502-e119c100-75a0-11ea-9a61-0909e88d6523.png)
![history-card2](https://user-images.githubusercontent.com/36473471/78347506-e1b25780-75a0-11ea-9fed-934495cf29b0.png)

**Comment by basnijholt** [comment]
I am not sure how this can be fixed. Because making it white will make it less visible in other parts.

**Comment by basnijholt** [comment]
Maybe I could decrease the transparency?

**Comment by basnijholt** [comment]
Fixed in https://github.com/basnijholt/lovelace-ios-dark-mode-theme/commit/0f050901ae2f114ae607fb402e256881ae58ca33.
