### ISSUE TITLE
Make “show entries for” and “period” text visible in log and history panels

### ISSUE THREAD

**Issue by grahamw72** [basnijholt/lovelace-ios-dark-mode-theme#42]
Please add this code to your theme to make “show entries for” and “period” text in log and history  panels match theme primary text colour.

lumo-body-text-color: "var(--primary-text-color)"

**Comment by basnijholt** [comment]
Fixed in f4a63a7. Thanks!

**Comment by grahamw72** [comment]
Thank you for updating, it was my OCD kicking in. Many thanks for creating this cool theme mate.

**Comment by basnijholt** [comment]
Great! Also check out https://github.com/basnijholt/lovelace-ios-themes

Which is a generalization and contains all backgrounds easily.

**Comment by grahamw72** [comment]
👍
