### ISSUE TITLE
wrong color after update to  0.108.2

### ISSUE THREAD

**Issue by centralhardware** [basnijholt/lovelace-ios-dark-mode-theme#43]
![image](https://user-images.githubusercontent.com/26829359/78968256-43893900-7b2e-11ea-93fd-5ffb08ac749f.png)

**Comment by brendanmullan** [comment]
+1 for this issue

**Comment by mikalauskas** [comment]
add this to the theme’s yaml
`sidebar-background-color: var(--primary-background-color) `
