### ISSUE TITLE
Issue with "Update Available" with HassIO >0.109 

### ISSUE THREAD

**Issue by Swampen** [basnijholt/lovelace-ios-dark-mode-theme#47]
I have HassIO verstion 0.109.2 and it is hard to read the text in the "Update Available" notification says.
![image](https://user-images.githubusercontent.com/32768682/80950837-efa10580-8df6-11ea-9aa7-584133a6f60a.png)

**Comment by basnijholt** [comment]
This is definitely a bug! I will check whether it can be fixed.

**Comment by basnijholt** [comment]
The CSS property is `update-heading` however I am unable to find how to set its color ATM.

**Comment by basnijholt** [comment]
`--paper-card-header-color` might be it, see https://github.com/PolymerElements/paper-card/issues/64

**Comment by Swampen** [comment]
After lurking in the Home Assistant repo, it looks like the update card uses hardcoded CSS style.
[hassio-update.ts](https://github.com/home-assistant/frontend/blob/82f80db558ceaab1d1cbe54fbfe2e2165e7cacd5/hassio/src/dashboard/hassio-update.ts#L166)
Not sure if we can actually change the text color?

**Comment by basnijholt** [comment]
@Swampen, I have opened https://github.com/home-assistant/frontend/pull/5754!

**Comment by basnijholt** [comment]
This has been fixed upstream!

Not sure if it will be in 0.109.5 or 0.110.
