### ISSUE TITLE
Some text & icon black in Supervisor - hard to read

### ISSUE THREAD

**Issue by sparkydave1981** [basnijholt/lovelace-ios-dark-mode-theme#48]
I have noticed in the Supervisor tab there is black text & icon on a dark background making it hard to read.  Not sure if it is also in other locations.

eg: the text displaying which version is available in the below screenshot, also the icon

![image](https://user-images.githubusercontent.com/7628509/81240221-64fc1880-9039-11ea-96df-008a5a258df0.png)

**Comment by basnijholt** [comment]
please see #47
