### ISSUE TITLE
Cosmetic issue when Updates are available

### ISSUE THREAD

**Issue by adandl** [basnijholt/lovelace-ios-dark-mode-theme#49]
![image](https://user-images.githubusercontent.com/58300252/81277494-c978a100-9054-11ea-8ccb-f26708701dab.png)

Black color on dark grey background is almost not visible.
Needs adjustment please.

Thank you!

**Comment by basnijholt** [comment]
Please search in closed issues:
- https://github.com/basnijholt/lovelace-ios-dark-mode-theme/issues/48
- https://github.com/basnijholt/lovelace-ios-dark-mode-theme/issues/47

This is fixed upstream.
