### ISSUE TITLE
"custom header" is no longer an active Project (since 10/2020)

### ISSUE THREAD

**Issue by Swiftrail84** [basnijholt/lovelace-ios-dark-mode-theme#66]
Hello. Since Okt. 2020 _custom header_ is no longer an active project. There is no download option in HACS. Do you have an alternative way?

**Comment by basnijholt** [comment]
Yes, try out https://github.com/basnijholt/lovelace-ios-themes

**Comment by Swiftrail84** [comment]
Thank you very much for you quick help!!! I´ve already installed the "iOS Dark Mode Theme". And i integrated

`custom_header:
  background: rgba(155, 155, 155, 0.25)
  compact_mode: true
  button_text:
    options: '{{ hours24 }}:{{ minutesLZ }}'`

to the RAW-Editor. But i couldn´t change the color. There is no reaction.

By the way: You should change the _custom header_ Information: 
<img width="849" alt="Bildschirmfoto 2021-07-06 um 12 54 02" src="https://user-images.githubusercontent.com/68839593/124588620-4e2d9d80-de59-11eb-8c00-12619065550c.png">

**Comment by basnijholt** [comment]
https://github.com/basnijholt/lovelace-ios-dark-mode-theme/commit/555c937dc9b5ab539c3a7c9d6ecd21db33796bac

**Comment by Swiftrail84** [comment]
Ok. This describes how to change the background image. Correctly?! But I would like to change the background color of the header. I would like to have the same color as it is on the left side. This should be 44, 44, 46, 1. Or: 2C2C2E.
<img width="1280" alt="Bildschirmfoto 2021-07-06 um 13 03 50" src="https://user-images.githubusercontent.com/68839593/124589766-a5803d80-de5a-11eb-94ea-5795e6501a10.png">

**Comment by basnijholt** [comment]
Again, try https://github.com/basnijholt/lovelace-ios-themes

That issue is fixed there.

**Comment by Swiftrail84** [comment]
Sorry, maybe I misunderstood you. "lovelace-ios-themes" seems like an update of "iOS Dark Mode Theme"?! I'll try it out right away!

**Comment by basnijholt** [comment]
Great :tada:

Will you close this issue?
