### ISSUE TITLE
Light icon no colour change

### ISSUE THREAD

**Issue by lonebaggie** [basnijholt/lovelace-ios-dark-mode-theme#7]
Light bulbs in Glance cards don't change colour when turned on . Solid white in both on and off state

**Comment by basnijholt** [comment]
For me the lights are in the color of the lights. 

I don't have lights that can only go on it off yet. 

If you figure out what setting up change you could submit a PR (or I'll fix it!)

**Comment by neerajdixit** [comment]
you could change
state-icon-active-color: "rgba(255, 214, 10, 1)"
under # States and Badges

**Comment by basnijholt** [comment]
@neerajdixit, thanks!

@lonebaggie, I have implemented the above suggestion.

Can you check if it works?

**Comment by basnijholt** [comment]
Actually, I checked myself. It works! 😄
