### ISSUE TITLE
ios-dark-mode.yaml contains duplicate key

### ISSUE THREAD

**Issue by Alexamig** [basnijholt/lovelace-ios-dark-mode-theme#76]
Gives an error in the latest version. Home Assistant 2022.03.3

Logger: homeassistant.util.yaml.loader
Source: util/yaml/loader.py:270
First occurred: 21:36:59 (6 occurrences)
Last logged: 21:36:59
YAML file /config/themes/ios-dark-mode/ios-dark-mode.yaml contains duplicate key "mdc-text-field-ink-color". Check lines 85 and 92
YAML file /config/themes/ios-dark-mode/ios-dark-mode.yaml contains duplicate key "mdc-text-field-label-ink-color". Check lines 86 and 93
YAML file /config/themes/ios-dark-mode/ios-dark-mode.yaml contains duplicate key "mdc-select-fill-color". Check lines 88 and 94
YAML file /config/themes/ios-dark-mode/ios-dark-mode.yaml contains duplicate key "mdc-select-label-ink-color". Check lines 89 and 95
YAML file /config/themes/ios-dark-mode/ios-dark-mode.yaml contains duplicate key "mdc-select-ink-color". Check lines 87 and 96

**Comment by basnijholt** [comment]
Fixed in 48c700c321da71aa75939662997a65ddebcce114.
