### ISSUE TITLE
Change primary color

### ISSUE THREAD

**Issue by aferraz** [basnijholt/lovelace-ios-dark-mode-theme#8]
Hi,
 I have changed primary color but, on Android, if I add the Chrome Page on Home screen I have an orange bar at the top.
Do you know how I can change it ?

Thanks

**Comment by basnijholt** [comment]
Did you install `cch`? (step 3 [here](https://github.com/basnijholt/lovelace-ios-dark-mode-theme#installation))

If you do not use that you can choose change [this](https://github.com/basnijholt/lovelace-ios-dark-mode-theme/blob/master/themes/ios-dark-mode.yaml#L8) line.

**Comment by aferraz** [comment]
thanks
