### ISSUE TITLE
Borders on all entities after the latest Home Assistant 2022.11.0 upgrade

### ISSUE THREAD

**Issue by quinzico** [basnijholt/lovelace-ios-dark-mode-theme#82]
I have updated to the latest available Home Assistant version.
I have cleared the cache of my browser.
I have tried a different browser to see if it is related to my browser.

**Describe the issue you are experiencing:**

After the upgrade of HA to version Home Assistant 2022.11.0, all cards have a white border.

![image](https://user-images.githubusercontent.com/57102800/199710170-5c5a66f3-1c34-488a-be62-4895b80f45f2.png)

**Describe the behavior you expected**

It should not have the white border, like the previous version
**Steps to reproduce the issue**

1.Upgrade HA
2. Use a darker background with not white cards.
**What version of Home Assistant Core has the issue?**

core-2022.11.0
**What was the last working version of Home Assistant Core?**

core-2022.10.5
**In which browser are you experiencing the issue with?**

Firefox 102.4.0esr, Iphone Home Assistant APP,
**Which operating system are you using to run this browser?**

Windows 10
**State of relevant entities**

Ive found it on all cards:

Buttons,custom:button-card, type: media-control, type: custom:mini-graph-card, type: gauge, type: entities, type: thermostat.

Everything that i put on the frontend has the issue, except vertical/horizontal stack

**Comment by quinzico** [comment]
I've added:

  ha-card-border-width: 0

To ios-themes.yaml on the section of my theme and now it's ok.

**Comment by basnijholt** [comment]
I just fixed this in the master branch.
