### ISSUE TITLE
gauge card color

### ISSUE THREAD

**Issue by aferraz** [basnijholt/lovelace-ios-dark-mode-theme#9]
Hi,
 redefine label-badge-red on the theme change red color also for gauge card.

Thanks
 Alessandro

**Comment by basnijholt** [comment]
Could you post a screenshot of the thing you want to change?

**Comment by aferraz** [comment]
![image](https://user-images.githubusercontent.com/3168680/69464294-35549f00-0d7e-11ea-889b-84ea9fd19b8f.png)
This should be red

**Comment by basnijholt** [comment]
I don’t think that fits with the theme. I’ll try it tomorrow though.

**Comment by aferraz** [comment]
Thanks @basnijholt, no problem take your time, but I'm pretty sure, removing label-badge-red  from theme resolve the issue.

**Comment by basnijholt** [comment]
![image](https://user-images.githubusercontent.com/6897215/69469081-3d690a80-0d8f-11ea-8392-b371d9e3a0f4.png)
it would change this one too.

**Comment by aferraz** [comment]
I know

**Comment by TinusK** [comment]
For me it looks like this:
Default theme:
![image](https://user-images.githubusercontent.com/27996194/69493538-0fc7b280-0eb0-11ea-9a57-72f6ffc47af2.png)
This theme:
![image](https://user-images.githubusercontent.com/27996194/69493555-41407e00-0eb0-11ea-8744-c5e60380d4a0.png)

**Comment by basnijholt** [comment]
@TinusK, how would you like it to be then?

**Comment by TinusK** [comment]
The inside should be the same color as surrounding the gauge (like in default: 0.0 W has a white background or complete transparent background). The inside should be transparent.

The actual value gauge background should not be that Black.... maybe light grey (as with default theme)?

**Comment by basnijholt** [comment]
Unfortunately, that is `--primary-background-color`, so making it another color would not make the theme "*dark*" anymore.

**Comment by TinusK** [comment]
Ah, ok, I understand.... Transparent is not an option? The inside maybe 100% and the background for the Gauge value maybe 70% Transparent?

**Comment by PorreKaj** [comment]
Bummer, we need a better gauge component.

**Comment by PorreKaj** [comment]
I added this to the ios-dark-mode.yaml to get the gauge to show red:
label-badge-red: rgba(195, 66, 63, 0.8)

**Comment by basnijholt** [comment]
Closing as wont-fix.
